Diplom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog1.urls')),
    path('pyhton/', include('blog2.urls')),
    path('registration/', include('blog3.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog1/urls.py
from django.contrib import admin
from blog1 import views
from django.urls import path, include
app_name = "blog1"

urlpatterns = [
    path('', views.home, name='home'),
    path('course/', views.course, name='course'),
    path('about', views.about, name='about'),
]

blog2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from blog2 import views
from django.urls import path, include
app_name = "blog2"

urlpatterns = [
    path('python/', views.python, name='python'),
    path('book', views.book, name='book'),
    path('video', views.video, name='video'),
    path('comment', views.comment, name='comment'),
    path('search_video', views.search_video, name='search_video'),
    path('search_book', views.search_book, name='search_book'),
    path('Run/', views.run, name='run'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog3/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from blog3 import views
from django.urls import path, include
app_name = "blog3"

urlpatterns = [
    path('registration', views.registration, name='registration'),
    path('signup', views.signup, name='signup'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog1/models.py
from django.db import models

# Create your models here.

blog1/views.py
from django.shortcuts import render
from django.contrib.auth.views import login_required
# Create your views here.


def home(request):
    return render(request, 'blog1/index.html')


def course(request):
    return render(request, 'blog1/Course.html')


def about(request):
    return render(request, 'blog1/about.html')

blog1/templates/blog1/about.html
{% extends 'blog1/base.html' %}
{% load static %}
{% block content %}
  <nav>
        <div class = "logo">
            <img src="{% static 'blog1/images/logo.png' %}" alt="">
            <p class = "animation-text">SKILLCARE</p>
        </div>
        <div class = "navv">
            <a class = "home animation-text" id = "home" href="{% url 'blog1:home' %}">Home</a>
            <div class = "span1" id = "span1"></div>
        </div>
        <div class = "navv">
            <a class = "coursee animation-text " id = "course" href="{% url 'blog1:course' %}">Course</a>
            <div class = "span2" id = "span2"></div>
        </div>
        <div class = "navv">
            <a class = "about animation-text menuus" id = "about" href="{% url 'blog1:about' %}">About</a>
            <div class = "span3 spann" id = "span3"></div>
        </div>
        <div class = "navv">
            <a class = "log animation-text" id = "log" href="{% url 'blog3:registration' %}">Registration</a>
            <div class = "span5" id = "span5"></div>
        </div>
        <a href=""{% url 'blog3:signup' %} class = "login">Sign up</a>
    </nav>
      <section class = "learning">
        <div class = "learn1">
            <div class = "learn_name">
                <p class = "l_n1">Benefits Of Learning From</p>
                <p class = "l_n2">SkillCare</p>
            </div>
            <p class = "learn_data">Lorem ipsum dolor sit amet consectetur adipisicing. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo accusantium corporis assumenda necessitatibus mollinus tempore labore nostrum.</p>
            <div class = "learn_btn">
                <a href="./Course.html" class = "learnbt">Start learning</a>
                <a href="https://en.wikipedia.org/wiki/List_of_programming_languages">Read more</a>
            </div>
        </div>

        <div class = "learn2">
            <div class = "learn_design">
                <div class = "dsg">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>

                <div class = "dsg">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>

                <div class = "dsg">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>

                <div class = "dsg">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>

                <div class = "dsg">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>

                <div class = "dsg">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
            <img class = "Learn_img" src="{% static 'blog1/images/Learn.png' %}" alt="">
            <div class = "learn_play">
                <div class = "play_dsn">
                    <img src="{% static 'blog1/images/Play.png' %}" alt="">
                </div>
            </div>
        </div>
    </section>

    <section class = "interest">
            <p>Are you interested in becoming an instructor</p>
            <a class = "btn btn-primary" href = "https://www.zippia.com/instructor-jobs/">Join with us</a>
    </section>


{% endblock %}

blog1/templates/blog1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blog1/css/style.css'  %}">
    <link rel="stylesheet" href="{% static 'blog1/css/animation.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


    <title>Diplom</title>
</head>
<body>
    <div class = "body"></div>
{% block content %}

    {% endblock  %}
 <section class = "foot">
    </section>


    <footer>
        <div class = "service">
            <h1>Services</h1>
            <a href="https://www.indeed.com/q-Online-Instructor-jobs.html?vjk=db8903dc7febc85f">Online Instructor</a>
            <a href="{% url 'blog1:course' %}">Premium E Course</a>
            <a href="{% url 'blog2:book' %}">E Books</a>
            <a href="{% url 'blog1:home' %}">Our Blogs</a>
        </div>
        <div class = "information">
            <h1>Information</h1>
            <a href="{% url 'blog3:registration' %}">Join us</a>
            <a href="https://www.groupon.com/coupons/amazon">Get Promo</a>
            <a href="https://support.squarespace.com/hc/en-us/articles/115015517328-Premium-features">Premium Feature</a>
            <a href="https://www.thefreedictionary.com/schedule">Schedule</a>
        </div>
        <div class = "company">
            <h1>Company</h1>
            <a href="https://www.gov.uk/set-up-business-partnership">Patnership</a>
            <a href="https://termify.io/terms-of-use-generator?gclid=CjwKCAiAl-6PBhBCEiwAc2GOVGW482XOXkuA71T9De24nJPqZ4KMsBoZWmHffZqT-xFhspr17IN98xoChiUQAvD_BwE">Terms of Use</a>
            <a href = "{% url 'blog1:about' %}">About</a>
            <a href="{% url 'blog1:about' %}">Contact</a>
        </div>
        <div class = "get_in">
            <h1>Get In Touch</h1>
            <p>Follow us on social media and stay updated with the latest information bout our services</p>
            <div class = "contact_logo">
                <img src="{% static 'blog1/images/instagram.jpg' %}" alt="">
                <img src="{% static 'blog1/images/tg.jpg' %}" alt="">
                <img src="{% static 'blog1/images/twitter.jpg' %}" alt="">
                <img src="{% static 'blog1/images/facebook.jpg' %}" alt="">
            </div>
        </div>
    </footer>

</body>
<script src="{% static 'blog1/javascript/main.js' %}"></script>
<script src="{% static 'blog1/javascript/animation.js' %}"></script>
</html>