Diplom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog1.urls')),
    path('pyhton/', include('blog2.urls')),
    path('registration/', include('blog3.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog1/urls.py
from django.contrib import admin
from blog1 import views
from django.urls import path, include
app_name = "blog1"

urlpatterns = [
    path('', views.home, name='home'),
    path('course/', views.course, name='course'),
    path('about', views.about, name='about'),
]

blog2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from blog2 import views
from django.urls import path, include
app_name = "blog2"

urlpatterns = [
    path('python/', views.python, name='python'),
    path('book', views.book, name='book'),
    path('video', views.video, name='video'),
    path('comment', views.comment, name='comment'),
    path('search_video', views.search_video, name='search_video'),
    path('search_book', views.search_book, name='search_book'),
    path('Run/', views.run, name='run'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog3/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from blog3 import views
from django.urls import path, include
app_name = "blog3"

urlpatterns = [
    path('registration', views.registration, name='registration'),
    path('signup', views.signup, name='signup'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog2/models.py
from django.db import models

# Create your models here.
from django.db.models import CASCADE


class Book(models.Model):
    image = models.ImageField(upload_to='Model_images')
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Comment(models.Model):
    name = models.CharField(max_length=50)
    comment = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class Menu(models.Model):
    name = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name


class Video(models.Model):
    menu = models.ForeignKey(Menu, on_delete=CASCADE, blank=True)
    name = models.CharField(max_length=100, blank=True)
    video = models.FileField(upload_to='Model_videos', blank=True)

    def __str__(self):
        return self.name


class Menu_part(models.Model):
    menu_name = models.ForeignKey(Menu, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class Menu_date(models.Model):
    menu_part_name = models.ForeignKey(Menu_part, on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=200, blank=True)
    main = models.CharField(max_length=600, blank=True)

    def __str__(self):
        return self.name

blog2/forms.py
from django import forms
from django.forms import ModelForm

from .models import *


class FormComment(ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'comment')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'enter name'
            }),

            'comment': forms.TextInput(attrs={
                'class': 'form-control',
                'row': '10',
                'placeholder': 'enter your comment',
            })
        }

blog2/views.py
from django.contrib.admin.templatetags.admin_list import pagination
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

# Create your views here.
from django.views.decorators.http import require_GET

from blog2.forms import FormComment
from blog2.models import Book, Comment, Video, Menu, Menu_part


@login_required(login_url='blog3:signup')
def python(request):
    books = Book.objects.all()

    menus = Menu.objects.all()

    menu_parts = Menu_part.objects.all()
    context = {
        'book': books,
        'menu': menus,
        'menu_part': menu_parts,
    }
    return render(request, 'blog2/python.html', context)


@require_GET
def search_book(request):
    book_query = request.GET.get('query_book')
    book_set = Book.objects.filter(name__icontains=book_query)
    context = {
        "book_search": book_set,
    }

    return render(request, 'blog2/search_book.html', context)


def book(request):
    books = Book.objects.all()
    book_count = books.count()
    p = Paginator(books, 8)
    page_number = request.GET.get('page')
    page_objects = p.get_page(page_number)

    context = {
        'book': page_objects,
        'book_count': book_count,
    }
    return render(request, 'blog2/book.html', context)


@require_GET
def search_video(request):
    video_query = request.GET.get('query_video')
    video_set = Video.objects.filter(name__icontains=video_query)
    context = {
        "video_search": video_set,
    }

    return render(request, 'blog2/search_video.html', context)


def video(request):
    videos = Video.objects.all()
    video_count = videos.count()

    p = Paginator(videos, 6)
    page_number = request.GET.get('page')
    page_objects = p.get_page(page_number)

    context = {
        "video": page_objects,
        "video_count": video_count,
    }
    return render(request, 'blog2/video.html', context)


def comment(request):
    comments = Comment.objects.all()

    enter_comments = FormComment(request.POST)
    if request.POST:
        enter_comments = FormComment(request.POST)
        if enter_comments.is_valid():
            form_comment = enter_comments.save(commit=True)
            form_comment.post = Comment.objects.all()
            form_comment.save()

            return redirect('blog2:comment')

    context = {
        'comment': comments,
        'enter_comment': enter_comments,
    }
    return render(request, 'blog2/comment.html', context)


def run(request):
    return render(request, 'blog2/Run.html')

blog2/templates/blog2/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blog2/css/py_style.css' %}">
    <link rel="stylesheet" href="{% static 'blog2/css/animation.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


    <title>Diplom</title>
</head>
<body>
    <div class = "body"></div>
    <nav>
        <div class = "logo">
            <img src="{% static 'blog2/images/Logo.png' %}" alt="">
            <p class = "animation-text">SKILLCARE</p>
        </div>
        <div class = "navv">
            <a class = "home animation-text" id = "home" href="{% url 'blog1:home' %}">Home</a>
            <div class = "span1" id = "span1"></div>
        </div>
        <div class = "navv">
            <a class = "coursee animation-text  menuu " id = "course" href="{% url 'blog1:course' %}">Course</a>
            <div class = "span2 spaan" id = "span2"></div>
        </div>
        <div class = "navv">
            <a class = "about animation-text" id = "about" href="{% url 'blog1:about' %}">About</a>
            <div class = "span3" id = "span3"></div>
        </div>
        <div class = "navv">
            <a class = "log animation-text" id = "log" href="{% url 'blog3:registration' %}">Registration</a>
            <div class = "span5" id = "span5"></div>
        </div>
        <a href="{% url 'blog3:signup' %}" class = "login">Sign up</a>
    </nav>

     <div  class = "python_logo select-div-animation">
        <img class = "p_logo_img" src="{% static 'blog2/images/logo.svg.png' %}" alt="">
        <div class = "p_logo_p">
            <p class = "logo_p1">P</p>
            <p class = "logo_p2">y</p>
            <p class = "logo_p3">t</p>
            <p class = "logo_p4">h</p>
            <p class = "logo_p5">o</p>
            <p class = "logo_p6">n</p>
        </div>
    </div>
{% block content %}


{% endblock %}




<section class = "foot">
</section>
   <footer>
        <div class = "service">
            <h1>Services</h1>
            <a href="https://www.indeed.com/q-Online-Instructor-jobs.html?vjk=db8903dc7febc85f">Online Instructor</a>
            <a href="{% url 'blog1:course' %}">Premium E Course</a>
            <a href="">E Books</a>
            <a href="{% url 'blog1:home' %}">Our Blogs</a>
        </div>
        <div class = "information">
            <h1>Information</h1>
            <a href="">Join us</a>
            <a href="https://www.groupon.com/coupons/amazon">Get Promo</a>
            <a href="https://support.squarespace.com/hc/en-us/articles/115015517328-Premium-features">Premium Feature</a>
            <a href="https://www.thefreedictionary.com/schedule">Schedule</a>
        </div>
        <div class = "company">
            <h1>Company</h1>
            <a href="https://www.gov.uk/set-up-business-partnership">Patnership</a>
            <a href="https://termify.io/terms-of-use-generator?gclid=CjwKCAiAl-6PBhBCEiwAc2GOVGW482XOXkuA71T9De24nJPqZ4KMsBoZWmHffZqT-xFhspr17IN98xoChiUQAvD_BwE">Terms of Use</a>
            <a href = "{% url 'blog1:about' %}">About</a>
            <a href="{% url 'blog1:about' %}">Contact</a>
        </div>
        <div class = "get_in">
            <h1>Get In Touch</h1>
            <p>Follow us on social media and stay updated with the latest information bout our services</p>
            <div class = "contact_logo">
                <img src="{% static 'blog1/images/instagram.jpg' %}" alt="">
                <img src="{% static 'blog1/images/tg.jpg' %}" alt="">
                <img src="{% static 'blog1/images/twitter.jpg' %}" alt="">
                <img src="{% static 'blog1/images/facebook.jpg' %}" alt="">
            </div>
        </div>
    </footer>

</body>
<script src="{% static 'blog1/javascript/main.js' %}"></script>
<script src="{% static 'blog1/javascript/animation.js' %}"></script>
</html>

blog2/templates/blog2/book.html
{% extends 'blog2/base2.html' %}
{% load static%}

{% block content %}

    <section class = "python_nav">
        <ul class = "p_ul">
            <li><a class ="animation-text" href="{% url 'blog2:python' %}">Home</a></li>
            <li><a class ="animation-text" href="">About</a></li>
            <li  class = "nav11" id = "nav3 "><a class ="animation-text" href="{% url 'blog2:book' %}">Books</a></li>
            <li id = "nav4"><a class ="animation-text" href="{% url 'blog2:video' %}">Videos</a></li>
            <li id = "nav5"><a class ="animation-text" href="{% url 'blog2:comment' %}">Comments</a></li>
            <li class = "lang">Lang
                <ul class = "langs">
                    <li class ="animation-text"> English</li>
                    <li class ="animation-text">Russian</li>
                    <li class ="animation-text">Uzbek</li>
                </ul>
            </li>
        </ul>
    </section>

    <section id = "bookss" class = "py_book">
        <form method="get" action="{% url 'blog2:search_book' %}" class = "py_search">
                        <input class="form-control tm-search-input" name="query_book" type="text" placeholder="Search..." aria-label="Search">
                        <button class="tm-search-button" type="submit">
                              <img src="{% static 'blog2/images/search.png' %}" alt="">
                        </button>
                    </form>

<h4 style="margin-left: -70% !important;">All books: {{ book_count}}</h4>


        <div  class = "book_part">
            {% for books in book %}
            <div class = "book_div">
                <img  src="{{ books.image.url }}" alt="">
                <p class = "book_name">{{ books.name}}</p>
                <p class = "py_btn">Download</p>
            </div>
            {% endfor %}
{##}
{#            <div class = "book_div">#}
{#                <img onclick="carusell('carusel2', 'bookss')" src="{% static 'blog2/images/book1.jpg' %}" alt="">#}
{#                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor</p>#}
{#                <p class = "py_btn">Download</p>#}
{#            </div>#}
{##}
{##}
{#            <div class = "book_div">#}
{#                <img onclick = "carusell('carusel2', 'bookss')" src="{% static 'blog2/images/book1.jpg' %}" alt="">#}
{#                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>#}
{#                <p class = "py_btn">Download</p>#}
{#            </div>#}
{##}
{##}
{#            <div class = "book_div">#}
{#                <img src="{% static 'blog2/images/book1.jpg' %}" alt="">#}
{#                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>#}
{#                <p class = "py_btn">Download</p>#}
{#            </div>#}

{#            <div class = "book_div">#}
{#                <img src="{% static 'blog2/images/book1.jpg' %}" alt="">#}
{#                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>#}
{#                <p class = "py_btn">Download</p>#}
{#            </div>#}
{#            <div class = "book_div">#}
{#                <img src="{% static 'blog2/images/book1.jpg' %}" alt="">#}
{#                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>#}
{#                <p class = "py_btn">Download</p>#}
{#            </div>#}

        </div>


    <div class="pagination">
  {% if book.has_previous %}
      <a href="?page={{ book.previous_page_number }}">Prev</a>
      {% else %}
      <a  href="#" class = "disabled">Prev</a>
    {% endif %}

         {% if book.has_previous  %}
      <a href="?page={{ book.previous_page_number }}">{{ book.previous_page_number }}</a>
        {% endif %}
      <a href="?page={{book.number}}" class="active">{{ book.number }}</a>
    {% if  book.has_next%}
      <a href="?page={{ book.next_page_number }}">{{ book.next_page_number }}</a>
    {% endif %}
    {% if book.has_next %}
      <a href="?page={{ book.next_page_number }}">Next</a>
    {% else %}
        <a class = "disabled" href="">Next</a>
    {% endif %}
    </div>

    </section>




    <!-- <div id="carusel2"  class = "carousel" data-flickity>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book3.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book4.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book3.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book4.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book4.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book4.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book3.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book4.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>

    </div> -->



{% endblock %}

blog2/templates/blog2/comment.html
{% extends 'blog2/base2.html' %}
{% load static%}

{% block content %}

  <section class = "python_nav">
        <ul class = "p_ul">
            <li id = "nav1"><a class ="animation-text" href="{% url 'blog2:python' %}">Home</a></li>
            <li id = "nav2"><a class ="animation-text" href="">About</a></li>
            <li id = "nav3"><a class ="animation-text" href="{% url 'blog2:book' %}">Books</a></li>
            <li id = "nav4"><a class ="animation-text" href="{% url 'blog2:video' %}">Videos</a></li>
            <li class = "nav11" id = "nav5"><a class ="animation-text" href="{% url 'blog2:comment' %}">Comments</a></li>
            <li class = "lang">Lang
                <ul class = "langs">
                    <li class ="animation-text"> English</li>
                    <li class ="animation-text">Russian</li>
                    <li class ="animation-text">Uzbek</li>
                </ul>
            </li>
        </ul>
    </section>

    <section class = "commenttaries">
        <div class = "comment1">
            <h1>Comments</h1>
            <div class="commentary">
            <p>{{ comment.count }} comments</p>
                {% for comments in comment %}
                <div class = "comments">
                    <div class = "comment_img">
                        <h1>{{ comments.name.split.0.0}}{{ comments.name.split.1.0 }}</h1>
                    </div>
                    <div class = "comment_p">
                        <h5>{{ comments.name}}</h5>
                        <p>{{ comments.comment }}</p>
                    </div>
                </div>
                {% endfor %}

{#                <div class = "comments">#}
{#                    <div class = "comment_img">#}
{#                        <h1>SH</h1>#}
{#                    </div>#}
{#                    <div class = "comment_p">#}
{#                        <h5>Shakhrizoda Sa`dullayeva</h5>#}
{#                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Atque tenetur tempore consequuntur laborum lor sit amet, consectetur adipisicing elit. Quo laudantium rerum voluptate ad voluptatum officiis officia, mollitia deserunt eos cumque?</p>#}
{#                    </div>#}
{#                </div>#}
{#                <div class = "comments">#}
{#                    <div class = "comment_img">#}
{#                        <h1>SH</h1>#}
{#                    </div>#}
{#                    <div class = "comment_p">#}
{#                        <h5>Shakhrizoda Sa`dullayeva</h5>#}
{#                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Atque tenetur tempore consequuntur laborum lor sit amet, consectetur adipisicing elit. Quo laudantium rerum voluptate ad voluptatum officiis officia, mollitia deserunt eos cumque?</p>#}
{#                    </div>#}
{#                </div>#}
{#                <div class = "comments">#}
{#                    <div class = "comment_img">#}
{#                        <h1>SH</h1>#}
{#                    </div>#}
{#                    <div class = "comment_p">#}
{#                        <h5>Shakhrizoda Sa`dullayeva</h5>#}
{#                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Atque tenetur tempore consequuntur laborum lor sit amet, consectetur adipisicing elit. Quo laudantium rerum voluptate ad voluptatum officiis officia, mollitia deserunt eos cumque?</p>#}
{#                    </div>#}
{#                </div>#}
            </div>
        </div>

        <div class = " forma">
            <h1>Commentary</h1>
            <form class = "form" action="" method="post">
                <br>
                {% csrf_token %}
                <h5>Your name:</h5>
                {{enter_comment.name}}
<br>
                 <h5>Your comment:</h5>
                {{ enter_comment.comment }}
<br>
                <button class = "btn btn-primary" type="submit">Send</button>
            </form>
        </div >

    </section>


{% endblock %}

blog2/templates/blog2/search_book.html
{% extends 'blog2/base2.html' %}
{% load static%}

{% block content %}

    <section class = "python_nav">
        <ul class = "p_ul">
            <li><a class ="animation-text" href="{% url 'blog2:python' %}">Home</a></li>
            <li><a class ="animation-text" href="">About</a></li>
            <li  class = "nav11" id = "nav3 "><a class ="animation-text" href="{% url 'blog2:book' %}">Books</a></li>
            <li id = "nav4"><a class ="animation-text" href="{% url 'blog2:video' %}">Videos</a></li>
            <li id = "nav5"><a class ="animation-text" href="{% url 'blog2:comment' %}">Comments</a></li>
            <li class = "lang">Lang
                <ul class = "langs">
                    <li class ="animation-text"> English</li>
                    <li class ="animation-text">Russian</li>
                    <li class ="animation-text">Uzbek</li>
                </ul>
            </li>
        </ul>
    </section>

    <section id = "bookss" class = "py_book">
        <form method="get" action="{% url 'blog2:search_book' %}" class = "py_search">
                        <input class="form-control tm-search-input" name="query_book" type="text" placeholder="Search..." aria-label="Search">
                        <button class="tm-search-button" type="submit">
                              <img src="{% static 'blog2/images/search.png' %}" alt="">
                        </button>
                    </form>

<h4 style="margin-left: -60% !important;">All search results: {{ book_search.count }}</h4>


        <div  class = "book_part">
            {% for books in book_search %}
            <div class = "book_div">
                <img  src="{{ books.image.url }}" alt="">
                <p class = "book_name">{{ books.name}}</p>
                <p class = "py_btn">Download</p>
            </div>
            {% endfor %}
{##}
{#            <div class = "book_div">#}
{#                <img onclick="carusell('carusel2', 'bookss')" src="{% static 'blog2/images/book1.jpg' %}" alt="">#}
{#                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor</p>#}
{#                <p class = "py_btn">Download</p>#}
{#            </div>#}
{##}
{##}
{#            <div class = "book_div">#}
{#                <img onclick = "carusell('carusel2', 'bookss')" src="{% static 'blog2/images/book1.jpg' %}" alt="">#}
{#                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>#}
{#                <p class = "py_btn">Download</p>#}
{#            </div>#}
{##}
{##}
{#            <div class = "book_div">#}
{#                <img src="{% static 'blog2/images/book1.jpg' %}" alt="">#}
{#                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>#}
{#                <p class = "py_btn">Download</p>#}
{#            </div>#}

{#            <div class = "book_div">#}
{#                <img src="{% static 'blog2/images/book1.jpg' %}" alt="">#}
{#                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>#}
{#                <p class = "py_btn">Download</p>#}
{#            </div>#}
{#            <div class = "book_div">#}
{#                <img src="{% static 'blog2/images/book1.jpg' %}" alt="">#}
{#                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>#}
{#                <p class = "py_btn">Download</p>#}
{#            </div>#}

        </div>


{#    <div class="pagination">#}
{#      <a href="#">Prev</a>#}
{#      <a href="#">1</a>#}
{#      <a href="#" class="active">2</a>#}
{#      <a href="#">3</a>#}
{#      <a href="#">4</a>#}
{#      <a href="#">5</a>#}
{#      <a href="#">6</a>#}
{#      <a href="#">Next</a>#}
{#    </div>#}

    </section>




    <!-- <div id="carusel2"  class = "carousel" data-flickity>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book3.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book4.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book3.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book4.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book4.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book4.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book3.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>
        <div class = "carousel-cell carousel_book">
            <div class = "book_div">
                <img src="book4.jpg" alt="">
                <p class = "book_name">Lorem ipsum dolor sit. Lorem, ipsum dolor.</p>
                <p class = "py_btn">Download</p>
            </div>
        </div>

    </div> -->



{% endblock %}